### ISSUE TITLE
help: Tailwind CSS not recompiling

### ISSUE THREAD

**Issue by tomirons** [danielroe/nuxt-ionic#17]
### 📚 What are you trying to do?

Use the `@nuxtjs/tailwindcss` module along with nuxt-ionic.

The dev server will recognize that the vue file has changed and reload the browser, but the css that get injected does not get replaced. It **does** however get replaced if I do one of the following.
1. Restart the dev server
2. Disable the nuxt-ionic module

**Comment by Lexpeartha** [comment]
> ### books What are you trying to do?
> 
> Use the `@nuxtjs/tailwindcss` module along with nuxt-ionic.
> 
> The dev server will recognize that the vue file has changed and reload the browser, but the css that get injected does not get replaced. It **does** however get replaced if I do one of the following.
> 
>     1. Restart the dev server
> 
>     2. Disable the nuxt-ionic module
>

I used stackblitz and from [fresh new project](https://stackblitz.com/edit/github-vjxlmr?file=pages/index.vue) I wasn't able to reproduce your issue. Could you provide reproduction template if you're still experiencing the issue? Few new versions of nuxt and tailwind module have been released since this issue was opened, so it is possible that something changed internally that fixed this issue.

**Comment by Lexpeartha** [comment]
If you're still experiencing this issue, please provide a reproduction
